image: "buildkite/hosted-agent-base-images:ubuntu-jammy"

cache:
  name: "build-cache"
  paths:
    - "~/rustcache"
    - "~/rustmodcache"
    - "/mise"
  size: "20g"

steps:
  - group: ":mag: QA"
    key: quality_checks
    steps:
      - label: ":rust: Lint"
        key: "lint"
        env:
          CARGO_HOME: "~/rustcache"
          CARGO_TARGET_DIR: "~/rustmodcache"
        commands:
          - "mise run lint"
        artifact_paths:
          - "clippy.sarif"
        plugins:
          - mise#v1.1.1: ~

      - label: ":rust: Test"
        key: "test"
        env:
          CARGO_HOME: "~/rustcache"
          CARGO_TARGET_DIR: "~/rustmodcache"
        commands:
          - "cargo nextest run --profile ci"
        artifact_paths:
          - "target/nextest/ci/junit.xml"
        plugins:
          - mise#v1.1.1: ~
